language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - pypy

env:
  - DJANGO=Django==1.6
  - DJANGO=https://github.com/django/django/archive/1.7c2.tar.gz

matrix:
  exclude:
    - python: 2.6
      env: DJANGO=https://github.com/django/django/archive/1.7c2.tar.gz

install:
  - pip install -q -e .
  - pip install -q $DJANGO
  - pip install -q --use-mirrors coveralls
  - pip install -q --use-mirrors nose

script: coverage run --source=menu `which django-admin.py` test --settings=menu.test_settings menu

after_success:
  coveralls
